services:
  ros2:
    image: lsd_iron:latest
    container_name: lsd_iron_test
    build:
      context: .
      dockerfile: Dockerfile

    #  Interactive mode
    stdin_open: true
    tty: true

    # Enable GPU support
    runtime: nvidia

    # Networking and IPC for ROS
    network_mode: host
    ipc: host
    # Needed to display graphical applications
    privileged: true

    environment:
      - XDG_RUNTIME_DIR=/tmp/runtime-root
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      # Allows graphical programs in the container.
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
      - ~/workspaces/ros2/iron/static_ws/src:/static_ws/src
      - ~/workspaces/ros2/iron/dynamic_ws/src:/dynamic_ws/src
      - ~/workspaces/ros2/iron/throwaway_ws/src:/throwaway_ws/src

    command:
      - /bin/bash
      - -c
      - |

        # Set folder for RUNTIME_DIR for RViz
        mkdir tmp/runtime-root && chmod 0700 tmp/runtime-root

        bash
